import { Product } from './hooks/useProduct'
const data: Array<Product> = [
  {
    id: '1',
    name: 'Apples',
    category: 'fruit',
    price: 2.95,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque ab quidem consequatur, maiores ratione in cumque magnam, aut culpa molestiae itaque, repellendus ex corrupti tenetur id repellat obcaecati ipsam quasi quae? Aperiam placeat eius perferendis adipisci quasi ratione sunt est nemo qui, esse nam totam reiciendis cumque, nulla sit, sequi quo quisquam deleniti modi soluta.',
    img: '/images/fruit/apples.jpg',
  },
  {
    id: '2',
    name: 'Aubergines',
    category: 'vegetables',
    price: 3.25,
    info: 'Explicabo dicta eligendi vel sint nobis aut a quidem quia nesciunt quas accusamus amet, consectetur expedita necessitatibus, accusantium commodi cum temporibus delectus veritatis mollitia exercitationem illum perferendis! Excepturi facere error ullam? Odit, necessitatibus quas! Ab sequi minus, quaerat vel accusamus laborum perspiciatis porro tempore, repellat alias nihil adipisci reiciendis, amet sapiente.',
    img: '/images/vegetables/aubergines.jpg',
  },
  {
    id: '3',
    name: 'Grapefruit',
    category: 'fruit',
    price: 3.95,
    info: 'Culpa quasi dolorum cumque in consequuntur, ad recusandae blanditiis minus quam fugit dignissimos, soluta est provident sapiente, fuga officiis laudantium repellat. Consequatur quas totam perferendis autem neque dignissimos est ipsam excepturi, accusamus ipsa sunt. Illum molestias inventore quas beatae in placeat veritatis blanditiis.',
    img: '/images/fruit/grapefruit.jpg',
  },
  {
    id: '4',
    name: 'Bell peppers',
    category: 'vegetables',
    price: 3.5,
    info: 'Distinctio exercitationem illo esse quibusdam, commodi error. Quidem animi sed modi ad ex quam, perspiciatis tenetur esse molestiae, velit distinctio vitae molestias atque nihil enim architecto vel dolorum voluptate doloremque! Magnam, corporis iste tempora odio sed dolor nostrum sunt!',
    img: '/images/vegetables/bell-peppers.jpg',
  },
  {
    id: '5',
    name: 'Grapes',
    category: 'fruit',
    price: 3.55,
    info: 'Explicabo dicta eligendi vel sint nobis aut a quidem quia nesciunt quas accusamus amet, consectetur expedita necessitatibus, accusantium commodi cum temporibus delectus veritatis mollitia exercitationem illum perferendis! Excepturi facere error ullam? Odit, necessitatibus quas! Ab sequi minus, quaerat vel accusamus laborum perspiciatis porro tempore, repellat alias nihil adipisci reiciendis, amet sapiente.',
    img: '/images/fruit/grapes.jpg',
  },
  {
    id: '6',
    name: 'Broccoli',
    category: 'vegetables',
    price: 3.25,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque ab quidem consequatur, maiores ratione in cumque magnam, aut culpa molestiae itaque, repellendus ex corrupti tenetur id repellat obcaecati ipsam quasi quae? Aperiam placeat eius perferendis adipisci quasi ratione sunt est nemo qui, esse nam totam reiciendis cumque, nulla sit, sequi quo quisquam deleniti modi soluta.',
    img: '/images/vegetables/broccoli.jpg',
  },
  {
    id: '7',
    name: 'Kiwi',
    category: 'fruit',
    price: 3.15,
    info: 'Molestiae, facere eveniet, eligendi obcaecati, aut quasi atque dolorem non cupiditate aliquam qui architecto aliquid illo doloremque ab perspiciatis rerum cum molestias repellendus itaque? Dicta pariatur dolorem repellendus reprehenderit cupiditate omnis, at sit, consectetur necessitatibus nostrum sint deleniti tempora assumenda nulla. Quos quasi repellendus rerum cupiditate, quas excepturi animi aut fuga.',
    img: '/images/fruit/kiwi.jpg',
  },
  {
    id: '8',
    name: 'Carrots',
    category: 'vegetables',
    price: 2.0,
    info: 'Minima quia explicabo ab assumenda distinctio quae. Incidunt, maiores. Enim, impedit accusamus voluptatibus unde possimus tenetur iure earum eaque quia harum molestias minus modi magni. Consequatur, beatae tempora aliquam veritatis dignissimos asperiores eius, perferendis dolor repudiandae sapiente quod repellat rerum voluptatem quidem praesentium laboriosam ipsa accusantium.',
    img: '/images/vegetables/carrots.jpg',
  },
  {
    id: '9',
    name: 'Oranges',
    category: 'fruit',
    price: 2.95,
    info: 'Possimus facilis molestiae, fuga totam cum, maiores atque rerum accusantium saepe voluptatem aspernatur? Porro aliquam iste voluptate vitae eos iusto tempora deserunt accusamus illum at! Commodi rerum deleniti maiores dolores. Sapiente tempore voluptatibus alias autem ullam quod illo repellendus. Amet officiis beatae in cumque sit quod qui, blanditiis sed aperiam enim minima!',
    img: '/images/fruit/oranges.jpg',
  },
  {
    id: '10',
    name: 'Cauliflower',
    category: 'vegetables',
    price: 3.25,
    info: 'Distinctio exercitationem illo esse quibusdam, commodi error. Quidem animi sed modi ad ex quam, perspiciatis tenetur esse molestiae, velit distinctio vitae molestias atque nihil enim architecto vel dolorum voluptate doloremque! Magnam, corporis iste tempora odio sed dolor nostrum sunt!',
    img: '/images/vegetables/cauliflower.jpg',
  },
  {
    id: '11',
    name: 'Pears',
    category: 'fruit',
    price: 3.75,
    info: 'Dolore voluptatem laboriosam porro aspernatur aliquid repudiandae iure officia repellat velit, eius facilis nulla, a enim ipsam minima? Dolor ipsa provident in eum, ipsum, reiciendis qui corporis delectus mollitia explicabo iste adipisci esse repudiandae velit necessitatibus? Assumenda excepturi alias earum voluptates blanditiis esse nulla minima accusamus debitis.',
    img: '/images/fruit/pears.jpg',
  },
  {
    id: '12',
    name: 'Courgettes',
    category: 'vegetables',
    price: 2.0,
    info: 'Minima quia explicabo ab assumenda distinctio quae. Incidunt, maiores. Enim, impedit accusamus voluptatibus unde possimus tenetur iure earum eaque quia harum molestias minus modi magni. Consequatur, beatae tempora aliquam veritatis dignissimos asperiores eius, perferendis dolor repudiandae sapiente quod repellat rerum voluptatem quidem praesentium laboriosam ipsa accusantium.',
    img: '/images/vegetables/courgettes.jpg',
  },
  {
    id: '13',
    name: 'Raspberries',
    category: 'fruit',
    price: 5.95,
    info: 'Minima quia explicabo ab assumenda distinctio quae. Incidunt, maiores. Enim, impedit accusamus voluptatibus unde possimus tenetur iure earum eaque quia harum molestias minus modi magni. Consequatur, beatae tempora aliquam veritatis dignissimos asperiores eius, perferendis dolor repudiandae sapiente quod repellat rerum voluptatem quidem praesentium laboriosam ipsa accusantium.',
    img: '/images/fruit/raspberries.jpg',
  },
  {
    id: '14',
    name: 'Cucumbers',
    category: 'vegetables',
    price: 3.0,
    info: 'Explicabo dicta eligendi vel sint nobis aut a quidem quia nesciunt quas accusamus amet, consectetur expedita necessitatibus, accusantium commodi cum temporibus delectus veritatis mollitia exercitationem illum perferendis! Excepturi facere error ullam? Odit, necessitatibus quas! Ab sequi minus, quaerat vel accusamus laborum perspiciatis porro tempore, repellat alias nihil adipisci reiciendis, amet sapiente.',
    img: '/images/vegetables/cucumbers.jpg',
  },
  {
    id: '15',
    name: 'Strawberries',
    category: 'fruit',
    price: 4.45,
    info: 'Distinctio exercitationem illo esse quibusdam, commodi error. Quidem animi sed modi ad ex quam, perspiciatis tenetur esse molestiae, velit distinctio vitae molestias atque nihil enim architecto vel dolorum voluptate doloremque! Magnam, corporis iste tempora odio sed dolor nostrum sunt!',
    img: '/images/fruit/strawberries.jpg',
  },
  {
    id: '16',
    name: 'Tomatoes',
    category: 'vegetables',
    price: 3.35,
    info: 'Molestiae, facere eveniet, eligendi obcaecati, aut quasi atque dolorem non cupiditate aliquam qui architecto aliquid illo doloremque ab perspiciatis rerum cum molestias repellendus itaque? Dicta pariatur dolorem repellendus reprehenderit cupiditate omnis, at sit, consectetur necessitatibus nostrum sint deleniti tempora assumenda nulla. Quos quasi repellendus rerum cupiditate, quas excepturi animi aut fuga.',
    img: '/images/vegetables/tomatoes.jpg',
  },
]
export default data
